trigger:
  branches:
    include:
    - '*'  
    - refs/tags/*
jobs:

- job: Windows
  pool: 'Hosted VS2017'

  variables:
    os_name: Windows

  strategy:
    matrix:
      node_8_x:
        node_version: 8.x
      node_10_x:
        node_version: 10.x

  steps:
  - template: scripts/azure-run-tests.yml

- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'

  variables:
    os_name: Linux

  strategy:
    matrix:
      node_8_x:
        node_version: 8.x
      node_10_x:
        node_version: 10.x

  steps:
  - template: scripts/azure-run-tests.yml

- job: OSX
  pool:
    vmImage: 'macOS 10.13'

  variables:
    os_name: OSX

  strategy:
    matrix:
      node_8_x:
        node_version: 8.x
      node_10_x:
        node_version: 10.x

  steps:
  - template: scripts/azure-run-tests.yml

- job: GitHub_Release
  displayName: Release to GitHub.com
  dependsOn: 
  - Windows
  - OSX
  - Linux
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v1.'))  
  steps:
  - task: GitHubRelease@0
    displayName: 'GitHub release (create)'
    inputs:
      gitHubConnection: 'github-zenithworks'
      title: Yarn Release version $(Build.SourceBranchName) 
      releaseNotesSource: input
      releaseNotes: | 
        Scikit Releases $(Build.SourceBranchName) 
       